export const FETCH_VARNISH_LOGS = 'varnishLogs/FETCH_VARNISH_LOGS';
export const FETCH_VARNISH_LOGS_SUCCESS = 'varnishLogs/FETCH_VARNISH_LOGS_SUCCESS';
export const FETCH_VARNISH_LOGS_FAILURE = 'varnishLogs/FETCH_VARNISH_LOGS_FAILURE';
